
# GitHub Actions workflow for backend CI/CD
name: Backend CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Unit Tests
      run: pytest tests/

    - name: Build Docker Image
      run: |
        docker build -t evade-backend:latest .

    - name: Push to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
        docker tag evade-backend:latest $DOCKER_USERNAME/evade-backend:latest
        docker push $DOCKER_USERNAME/evade-backend:latest

    - name: Deploy to AWS EKS
      run: |
        kubectl apply -f k8s/deployment.yaml
