name: CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install

      - name: Run Backend Tests
        working-directory: ./backend
        run: npm test

      - name: Run Frontend Tests
        working-directory: ./frontend
        run: npm test

      - name: Run Mobile Tests
        working-directory: ./mobile
        run: npm test

      - name: Run Desktop Tests
        working-directory: ./desktop
        run: npm test

  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Backend
        working-directory: ./backend
        run: npm run build

      - name: Build Frontend
        working-directory: ./frontend
        run: npm run build

      - name: Build Mobile
        working-directory: ./mobile
        run: npm run build

      - name: Deploy Backend
        run: |
          scp -r ./backend/build server:/var/www/evade-backend
          ssh server 'systemctl restart evade-backend'

      - name: Deploy Frontend
        run: |
          scp -r ./frontend/build server:/var/www/evade-frontend
          ssh server 'systemctl restart evade-frontend'

      - name: Deploy Mobile
        run: |
          scp -r ./mobile/build server:/var/www/evade-mobile
          ssh server 'systemctl restart evade-mobile'

  advanced_features:
    name: Enable New Features
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Test OnStar-Like Features
        working-directory: ./backend/onstar
        run: npm test

      - name: Test Viper/Compustar Security
        working-directory: ./backend/security
        run: npm test

      - name: Test Advanced Navigation
        working-directory: ./frontend/navigation
        run: npm test

      - name: Test Connectivity Features
        working-directory: ./mobile/connectivity
        run: npm test

      - name: Deploy OnStar-Like Features
        run: |
          scp -r ./backend/onstar/build server:/var/www/evade-onstar
          ssh server 'systemctl restart evade-onstar'

      - name: Deploy Security Features
        run: |
          scp -r ./backend/security/build server:/var/www/evade-security
          ssh server 'systemctl restart evade-security'

      - name: Deploy Advanced Navigation
        run: |
          scp -r ./frontend/navigation/build server:/var/www/evade-navigation
          ssh server 'systemctl restart evade-navigation'

      - name: Deploy Connectivity Features
        run: |
          scp -r ./mobile/connectivity/build server:/var/www/evade-connectivity
          ssh server 'systemctl restart evade-connectivity'
