name: CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install

      - name: Run Backend Tests
        working-directory: ./backend
        run: npm test

      - name: Run Frontend Tests
        working-directory: ./frontend
        run: npm test

      - name: Run Mobile Tests
        working-directory: ./mobile
        run: npm test

      - name: Run Desktop Tests
        working-directory: ./desktop
        run: npm test

  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Backend
        working-directory: ./backend
        run: npm run build

      - name: Build Frontend
        working-directory: ./frontend
        run: npm run build

      - name: Build Mobile
        working-directory: ./mobile
        run: npm run build

      - name: Deploy Backend
        run: |
          scp -r ./backend/build server:/var/www/evade-backend
          ssh server 'systemctl restart evade-backend'

      - name: Deploy Frontend
        run: |
          scp -r ./frontend/build server:/var/www/evade-frontend
          ssh server 'systemctl restart evade-frontend'

      - name: Deploy Mobile
        run: |
          scp -r ./mobile/build server:/var/www/evade-mobile
          ssh server 'systemctl restart evade-mobile'
