
name: DevOps CI/CD

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Images
        run: docker build -t backend:${{ github.sha }} backend/

      - name: Push Docker Images
        run: docker push backend:${{ github.sha }}

  infrastructure:
    needs: docker
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Apply Terraform
        run: terraform apply -auto-approve
