
name: Machine Learning CI

on:
  push:
    paths:
      - 'ml/**'
    branches:
      - main
  pull_request:
    paths:
      - 'ml/**'
    branches:
      - main

jobs:
  train-and-validate:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ml/requirements.txt

      - name: Train Model
        run: python ml/train.py

      - name: Validate Model
        run: python ml/validate.py
